# Generated by Django 4.2.21 on 2025-05-09 04:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FME_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SalePunchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sp_contact_no', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid 10 digit mobile number', regex='^\\d{10}$')])),
                ('sp_email', models.EmailField(max_length=254, unique=True)),
                ('sp_whatsapp_no', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid 10 digit mobile number', regex='^\\d{10}$')])),
                ('sp_insta_link', models.URLField(blank=True, null=True, unique=True)),
                ('sp_fb_link', models.URLField(blank=True, null=True, unique=True)),
                ('sp_google_review_link', models.URLField(blank=True, null=True, unique=True)),
                ('sp_gmap_link', models.URLField(blank=True, null=True, unique=True)),
                ('sp_discount_details', models.CharField(blank=True, max_length=255, null=True)),
                ('sp_custom_review_filter', models.BooleanField(default=True)),
                ('sp_additional_products', models.CharField(blank=True, max_length=255, null=True)),
                ('sp_logo', models.FileField(blank=True, null=True, upload_to='logo/')),
                ('sp_status', models.CharField(blank=True, choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=255, null=True)),
                ('sp_fme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_crm.fme_model')),
            ],
        ),
    ]
