# Generated by Django 4.2.21 on 2025-05-13 07:01

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FME_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SalePunchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_fme', models.CharField(blank=True, max_length=255, null=True)),
                ('sp_business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sp_contact_no', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid 10 digit mobile number', regex='^\\d{10}$')])),
                ('sp_email', models.EmailField(max_length=254)),
                ('sp_whatsapp_no', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid 10 digit mobile number', regex='^\\d{10}$')])),
                ('sp_insta_link', models.URLField(blank=True, null=True)),
                ('sp_fb_link', models.URLField(blank=True, null=True)),
                ('sp_google_review_link', models.URLField(blank=True, null=True)),
                ('sp_gmap_link', models.URLField(blank=True, null=True)),
                ('sp_discount_details', models.CharField(blank=True, max_length=255, null=True)),
                ('sp_custom_review_filter', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=255, null=True)),
                ('sp_additional_products', models.CharField(blank=True, max_length=255, null=True)),
                ('sp_logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('sp_status', models.CharField(blank=True, choices=[('active', 'active'), ('inactive', 'inactive')], default='inactive', max_length=255, null=True)),
                ('sp_web_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=255)),
                ('user_type', models.CharField(blank=True, choices=[('admin', 'admin'), ('collection agent', 'collection agent')], default='collection agent', max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('designation', models.CharField(blank=True, choices=[('Agent', 'Agent'), ('Field Executive', 'Field Executive')], default='Field Executive', max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
