# Generated by Django 4.2.21 on 2025-05-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salepunchmodel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
