# Generated by Django 4.2.21 on 2025-05-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0002_salepunchmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='salepunchmodel',
            name='sp_web_link',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
