# Generated by Django 4.2.21 on 2025-05-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0003_salepunchmodel_sp_web_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salepunchmodel',
            name='name',
        ),
        migrations.AlterField(
            model_name='salepunchmodel',
            name='sp_fme',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
