# Generated by Django 4.2.21 on 2025-05-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0007_alter_salepunchmodel_sp_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salepunchmodel',
            name='sp_custom_review_filter',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=255, null=True),
        ),
    ]
