# Generated by Django 4.2.21 on 2025-05-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0008_alter_salepunchmodel_sp_custom_review_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salepunchmodel',
            name='sp_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
