# Generated by Django 4.2.21 on 2025-05-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0010_alter_salepunchmodel_sp_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salepunchmodel',
            name='sp_logo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='logo/'),
        ),
    ]
