# Generated by Django 4.2.21 on 2025-05-10 04:16

import app_crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0011_alter_salepunchmodel_sp_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salepunchmodel',
            name='sp_logo',
            field=models.ImageField(blank=True, null=True, upload_to=app_crm.models.nameFile),
        ),
    ]
