# Generated by Django 4.2.21 on 2025-05-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0013_alter_salepunchmodel_sp_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, choices=[('Agent', 'Agent'), ('Field Executive', 'Field Executive')], default='Field Executive', max_length=255, null=True),
        ),
    ]
